apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - protocol: TCP
      port: 443           # Port inside the cluster (for HTTPS)
      targetPort: 443     # Port on the container
      nodePort: 30499     # Fixed NodePort (must be between 30000–32767)
